# Buildpack metadata for Eclipse Temurin JRE 21

api = "0.10"

[buildpack]
id = "heroku/temurin-jre21"
version = "1.0.0"
name = "Eclipse Temurin JRE 21"
homepage = "https://adoptium.net/"
description = "Heroku buildpack for Eclipse Temurin JRE 21 with HotSpot JVM"
keywords = ["java", "jre", "temurin", "eclipse", "adoptium", "hotspot"]

[[buildpack.licenses]]
type = "MIT"

[metadata]
include-files = ["bin/compile", "bin/detect", "bin/release", "README.md", "LICENSE"]

[[metadata.dependencies]]
id = "jre"
name = "Eclipse Temurin JRE"
version = "21.0.5+11"
uri = "https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.5%2B11/OpenJDK21U-jre_x64_linux_hotspot_21.0.5_11.tar.gz"
sha256 = ""
stacks = ["heroku-20", "heroku-22", "heroku-24"]

[[metadata.dependencies]]
id = "jre"
name = "Eclipse Temurin JRE"
version = "21.0.5+11"
uri = "https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.5%2B11/OpenJDK21U-jre_aarch64_linux_hotspot_21.0.5_11.tar.gz"
sha256 = ""
stacks = ["heroku-20", "heroku-22", "heroku-24"]

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "heroku-22"

[[stacks]]
id = "heroku-24"
